import * as generator from './generators.spec';
import { dateToString } from '../reports.spec';

//    The keys of the objects generated by this function are deliberately not CamelCase.  They specifically mirror the FormControlName values of elements in the Front-End
export function generateReportObject(reportGiven: object = {}): object {
  let reportRandom: object = {
    filing_frequency: generator.f3xFilingFrequency(),
    report_type_category: '',
    report_code: '',
    coverage_from_date: dateToString(generator.date()),
    coverage_through_date: '',
    date_of_election: dateToString(generator.date()),
    state_of_election: generator.state(false), //US Territories included
  };

  let report: object = { ...reportRandom, ...reportGiven };

  if (report['report_type_category'] == '')
    report['report_type_category'] = generator.f3xReportCategory(report['filing_frequency']);
  if (report['report_code'] == '')
    report['report_code'] = generator.f3xReportCode(report['filing_frequency'], report['report_type_category']);
  if (report['coverage_through_date'] == '')
    report['coverage_through_date'] = dateToString(
      generator.f3xCoverageThroughDate(report['coverage_from_date'], report['filing_frequency'])
    );

  return report;
}
