export const environment = {
  production: false,
  name: 'local',
  apiUrl: 'http://localhost:8080/api/v1',
  appTitle: 'FECfile',
  dcfConverterApiUrl: 'https://dev-efile-api.efdev.fec.gov/dcf_converter/v1',
  fecApiUrl: 'https://api.open.fec.gov/v1/',
  userCanSetFilingFrequency: true,
  loginDotGovAuthUrl: 'http://localhost:8080/oidc/authenticate',
  loginDotGovLogoutUrl: 'http://localhost:8080/oidc/logout',
  ffapiCommitteeIdCookieName: 'ffapi_committee_id',
  ffapiEmailCookieName: 'ffapi_email',
  ffapiLoginDotGovCookieName: 'ffapi_login_dot_gov',
  sessionIdCookieName: 'sessionid',
};
