const apiUrl = 'http://localhost:8080/api/v1';
export const environment = {
  production: false,
  name: 'local',
  apiUrl: apiUrl,
  appTitle: 'FECfile+',
  dcfConverterApiUrl: 'https://dev-efile-api.efdev.fec.gov/dcf_converter/v1',
  fecApiUrl: 'https://api.open.fec.gov/v1/',
  userCanSetFilingFrequency: true,
  loginDotGovAuthUrl: `${apiUrl}/oidc/authenticate`,
  loginDotGovLogoutUrl: `${apiUrl}/oidc/logout`,
  ffapiTimeoutCookieName: 'ffapi_timeout_local',
  sessionIdCookieName: 'sessionid',
  committee_data_source: 'test',
  form1m_link: 'https://webforms.stage.efo.fec.gov/webforms/form1/index.htm',
  showForm3: true,
  showSchedF: true,
  disableLogin: false,
  fecSpec: 8.5,
  showGlossary: true,
  webForms: 'https://webforms.stage.efo.fec.gov',
  whoCanUseLink: 'https://www.fec.gov/efiling/who-can-use-fecfile-plus?dialog=open',
  // run a dummy error reporting endpoint for local environment with:
  // node -e "require('http').createServer((req,res)=>{let b='';req.on('data',d=>b+=d);req.on('end',()=>{console.log(req.method,req.url,b);res.writeHead(204);res.end();});}).listen(7777)"
  errorReporting: {
    enabled: true,
    endpoint: '/frontend-error-report',
    sampleRates: {
      runtime: 1,
      promise: 1,
      http4xx: 1,
      http5xx: 1,
    },
    dedupeWindowMs: 30000,
    batchSize: 10,
    flushIntervalMs: 5000,
    maxMessageLength: 500,
    maxStackLength: 2000,
    maxPayloadBytes: 12000,
  },
};
