export const environment = {
  production: false,
  name: 'local',
  apiUrl: 'http://localhost:8080/api/v1',
  appTitle: 'FECfile',
  dcfConverterApiUrl: 'https://dev-efile-api.efdev.fec.gov/dcf_converter/v1',
  fecApiCommitteeUrl: 'https://api.open.fec.gov/v1/committee',
  fecApiKey: 'DEMO_KEY',
  userCanSetFilingFrequency: true,
  loginDotGovAuthUrl: 'http://localhost:8080/oidc/authenticate',
  loginDotGovLogoutUrl: 'http://localhost:8080/oidc/logout/',
  ffapiJwtCookieName: 'ffapi_jwt',
  ffapiCommitteeIdCookieName: 'ffapi_committee_id',
  ffapiEmailCookieName: 'ffapi_email',
};
