version: '3'

services:

  web:
    build:
      context: './front-end'
      dockerfile: './build-scripts/Dockerfile'
      args:
        - SNYK_AUTH_TOKEN
    image: fecfile-web
    container_name: fecfile-web
    restart: always
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - 8081:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    build:
      context: './proxy'
      dockerfile: Dockerfile
    image: fecfile-proxy
    container_name: fecfile-proxy
    restart: always
    volumes:
      - ./proxy/log:/var/log/nginx
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web
