services:
  angular-dev:
    build:
      context: ..
      dockerfile: front-end/Dockerfile
    volumes:
      - ..:/app
      - /app/front-end/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=1

  frontend-nginx:
    image: nginx:alpine
    depends_on:
      - angular-dev
    ports:
      - "${PORT:-4200}:${PORT:-4200}"
    volumes:
      - ../deploy-config/front-end-nginx-config/mime.types:/etc/nginx/mime.types:ro
      - ../deploy-config/front-end-nginx-config/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - PORT=${PORT:-4200}
      - FECFILE_APP_URL=${APP_URL:-http://localhost:4200}
      - FECFILE_API_URL=${API_URL:-http://localhost:8080}
      - CDN_STATIC_ASSET_CACHE_LENGTH_SECONDS=0