export const StartTransactionMenu = {
  sidebar: {
    addReceipt: 'Add a receipt',
    addDisbursement: 'Add a disbursement',
    addIndependentExpenditure: 'Add an independent expenditure',
    addLoansAndDebts: 'Add loans and debts',
  },
  accordion: {
    loans: 'LOANS',
    debts: 'DEBTS',
    contributionsFromIndividuals: 'CONTRIBUTIONS FROM INDIVIDUALS/PERSONS',
    contributionsFromRegisteredFilers: 'CONTRIBUTIONS FROM REGISTERED FILERS',
    contributionsToRegisteredFilers: 'CONTRIBUTIONS/EXPENDITURES TO/ON BEHALF OF REGISTERED FILERS',
    federalElectionActivityExpenditures: 'FEDERAL ELECTION ACTIVITY EXPENDITURES',
    otherExpenditures: 'OTHER EXPENDITURES',
    refunds: 'REFUNDS',
    transfers: 'TRANSFERS',
    other: 'OTHER',
  },
  links: {
    individualReceipt: 'Individual Receipt',
    returnedBouncedReceipt: 'Returned/Bounced Receipt',
    partnershipReceipt: 'Partnership Receipt',
    earmarkReceipt: 'Earmark Receipt',
    partyReceipt: 'Party Receipt',
    pacEarmarkReceipt: 'PAC Earmark Receipt',
    pacReceipt: 'PAC Receipt',
    refundContributionToOtherPoliticalCommittee: 'Refund of Contribution to Other Political Committee',
    jointFundraisingTransfer: 'Joint Fundraising Transfer',
    offsetsToOperatingExpenditures: 'Offsets to Operating Expenditures',
    otherReceipts: 'Other Receipts',
    individualReceiptNonContributionAccount: 'Individual Receipt - Non-contribution Account',
    otherCommitteeReceiptNonContributionAccount: 'Other Committee Receipt - Non-contribution Account',
    businessLaborOrganizationReceiptNonContributionAccount:
      'Business/Labor Organization Receipt - Non-contribution Account',
    contributionToCandidate: 'Contribution to Candidate',
    coordinatedPartyExpenditure: 'Coordinated Party Expenditure',
    independentExpenditure: 'Independent Expenditure',
    independentExpenditureVoid: 'Independent Expenditure - Void',
    hundredPercentFederalElectionActivityPayment: '100% Federal Election Activity Payment',
    creditCardPaymentForHundredPercentFederalElectionActivity: 'Credit Card Payment for 100% Federal Election Activity',
    otherDisbursement: 'Other Disbursement',
    loanReceivedFromBank: 'Loan Received from Bank',
    loanByCommittee: 'Loan By Committee',
    loanReceivedFromIndividual: 'Loan Received from Individual',
    debtOwedByCommittee: 'Debt Owed By Committee',
    debtOwedToCommittee: 'Debt Owed To Committee',
  },
} as const;
