import { TransactionType, TransactionTemplateMapType } from './transaction-type.model';
import { ScheduleIds } from './transaction.model';

export abstract class SchATransactionType extends TransactionType {
  scheduleId = ScheduleIds.A;

  //Labels
  override dateLabel = 'DATE RECEIVED';
  override amountInputHeader = 'Receipt information';
  override purposeDescripLabel = 'PURPOSE OF RECEIPT';

  // Mapping of schedule fields to the group input component form templates
  templateMap: TransactionTemplateMapType = {
    // Form fields
    last_name: 'contributor_last_name',
    first_name: 'contributor_first_name',
    middle_name: 'contributor_middle_name',
    prefix: 'contributor_prefix',
    suffix: 'contributor_suffix',
    street_1: 'contributor_street_1',
    street_2: 'contributor_street_2',
    city: 'contributor_city',
    state: 'contributor_state',
    zip: 'contributor_zip',
    employer: 'contributor_employer',
    occupation: 'contributor_occupation',
    organization_name: 'contributor_organization_name',
    committee_fec_id: 'donor_committee_fec_id',
    committee_name: 'donor_committee_name',
    candidate_fec_id: 'donor_candidate_fec_id',
    candidate_last_name: 'donor_candidate_last_name',
    candidate_first_name: 'donor_candidate_first_name',
    candidate_middle_name: 'donor_candidate_middle_name',
    candidate_prefix: 'donor_candidate_prefix',
    candidate_suffix: 'donor_candidate_suffix',
    candidate_office: 'donor_candidate_office',
    candidate_state: 'donor_candidate_state',
    candidate_district: 'donor_candidate_district',
    date: 'contribution_date',
    date2: '',
    memo_code: 'memo_code',
    amount: 'contribution_amount',
    balance: '',
    payment_to_date: '',
    interest_rate: '',
    due_date: '',
    interest_rate_setting: '',
    due_date_setting: '',
    secured: '',
    aggregate: 'contribution_aggregate',
    calendar_ytd: '',
    aggregate_general_elec_expended: '',
    general_election_year: '',
    purpose_description: 'contribution_purpose_descrip',
    text4000: 'text4000',
    category_code: '',
    election_code: 'election_code',
    election_other_description: 'election_other_description',
    secondary_name: '',
    secondary_street_1: '',
    secondary_street_2: '',
    secondary_city: '',
    secondary_state: '',
    secondary_zip: '',
    signatory_1_last_name: '',
    signatory_1_first_name: '',
    signatory_1_middle_name: '',
    signatory_1_prefix: '',
    signatory_1_suffix: '',
    signatory_1_date: '',
    signatory_2_last_name: '',
    signatory_2_first_name: '',
    signatory_2_middle_name: '',
    signatory_2_prefix: '',
    signatory_2_suffix: '',
    signatory_2_title: '',
    signatory_2_date: '',
    quaternary_committee_fec_id: '',
    quaternary_committee_name: '',
    quinary_committee_fec_id: '',
    quinary_committee_name: '',
    quinary_street_1: '',
    quinary_street_2: '',
    quinary_city: '',
    quinary_state: '',
    quinary_zip: '',
  };
}
