export enum Disbursement {
  OPERATING_EXPENDITURES = 'OPERATING EXPENDITURES',
  CONTRIBUTIONS_EXPENDITURES_TO_REGISTERED_FILERS = 'CONTRIBUTIONS/EXPENDITURES TO/ON BEHALF OF REGISTERED FILERS',
  OTHER_EXPENDITURES = 'OTHER EXPENDITURES',
  REFUND = 'REFUNDS',
  FEDERAL_ELECTION_ACTIVITY_EXPENDITURES = 'FEDERAL ELECTION ACTIVITY EXPENDITURES',
  COORDINATED_EXPENDITURES = 'COORDINATED_EXPENDITURES',
}

export type DisbursementType =
  | Disbursement.OPERATING_EXPENDITURES
  | Disbursement.CONTRIBUTIONS_EXPENDITURES_TO_REGISTERED_FILERS
  | Disbursement.OTHER_EXPENDITURES
  | Disbursement.REFUND
  | Disbursement.FEDERAL_ELECTION_ACTIVITY_EXPENDITURES;

export enum LoansAndDebts {
  LOANS = 'LOANS',
  DEBTS = 'DEBTS',
}

export type LoansAndDebtsType = LoansAndDebts.DEBTS | LoansAndDebts.LOANS;

export enum Receipt {
  CONTRIBUTIONS_FROM_INDIVIDUALS_PERSONS = 'CONTRIBUTIONS FROM INDIVIDUALS/PERSONS',
  CONTRIBUTIONS_FROM_REGISTERED_FILERS = 'CONTRIBUTIONS FROM REGISTERED FILERS',
  TRANSFERS = 'TRANSFERS',
  REFUNDS = 'REFUNDS',
  OTHER = 'OTHER',
}

export type ReceiptType =
  | Receipt.CONTRIBUTIONS_FROM_INDIVIDUALS_PERSONS
  | Receipt.CONTRIBUTIONS_FROM_REGISTERED_FILERS
  | Receipt.TRANSFERS
  | Receipt.REFUNDS
  | Receipt.OTHER;
