import type { LabelList } from '../utils/label.utils';

// Schedule A
export enum ScheduleATransactionTypes {
  // Contributions from Individuals/Persons
  INDIVIDUAL_RECEIPT = 'INDIVIDUAL_RECEIPT',
  TRIBAL_RECEIPT = 'TRIBAL_RECEIPT',
  PARTNERSHIP_RECEIPT = 'PARTNERSHIP_RECEIPT',
  IN_KIND_RECEIPT = 'IN_KIND_RECEIPT',
  RETURNED_BOUNCED_RECEIPT_INDIVIDUAL = 'RETURN_RECEIPT',
  EARMARK_RECEIPT = 'EARMARK_RECEIPT',
  CONDUIT_EARMARK_RECEIPT = 'CONDUIT_EARMARK_RECEIPT',
  CONDUIT_EARMARK_RECEIPT_DEPOSITED = 'CONDUIT_EARMARK_RECEIPT_DEPOSITED',
  CONDUIT_EARMARK_RECEIPT_UNDEPOSITED = 'CONDUIT_EARMARK_RECEIPT_UNDEPOSITED',
  RECEIPT_FROM_UNREGISTERED_ENTITY = 'RECEIPT_FROM_UNREGISTERED_ENTITY',
  RECEIPT_FROM_UNREGISTERED_ENTITY_RETURN = 'RECEIPT_FROM_UNREGISTERED_ENTITY_RETURN',
  // Contributions from Registered Filers
  PARTY_RECEIPT = 'PARTY_RECEIPT',
  PARTY_IN_KIND_RECEIPT = 'PARTY_IN_KIND_RECEIPT',
  PARTY_RETURN = 'PARTY_RETURN',
  PAC_RECEIPT = 'PAC_RECEIPT',
  PAC_IN_KIND_RECEIPT = 'PAC_IN_KIND_RECEIPT',
  PAC_EARMARK_RECEIPT = 'PAC_EARMARK_RECEIPT',
  PAC_CONDUIT_EARMARK = 'PAC_CONDUIT_EARMARK',
  PAC_CONDUIT_EARMARK_RECEIPT_DEPOSITED = 'PAC_CONDUIT_EARMARK_RECEIPT_DEPOSITED',
  PAC_CONDUIT_EARMARK_RECEIPT_UNDEPOSITED = 'PAC_CONDUIT_EARMARK_RECEIPT_UNDEPOSITED',
  PAC_RETURN = 'PAC_RETURN',
  CONTRIBUTION_FROM_CANDIDATE = 'CONTRIBUTION_FROM_CANDIDATE',
  IN_KIND_CONTRIBUTION_FROM_CANDIDATE = 'IN_KIND_CONTRIBUTION_FROM_CANDIDATE',
  // Transfers
  TRANSFER = 'TRANSFER',
  AUTHORIZED_COMMITTEE_TRANSFER = 'AUTHORIZED_COMMITTEE_TRANSFER',
  JOINT_FUNDRAISING_TRANSFER = 'JOINT_FUNDRAISING_TRANSFER',
  IN_KIND_TRANSFER = 'IN_KIND_TRANSFER',
  IN_KIND_TRANSFER_FEDERAL_ELECTION_ACTIVITY = 'IN_KIND_TRANSFER_FEDERAL_ELECTION_ACTIVITY',
  JF_TRANSFER_NATIONAL_PARTY_CONVENTION_ACCOUNT = 'JF_TRANSFER_NATIONAL_PARTY_CONVENTION_ACCOUNT',
  JF_TRANSFER_NATIONAL_PARTY_RECOUNT_ACCOUNT = 'JF_TRANSFER_NATIONAL_PARTY_RECOUNT_ACCOUNT',
  JF_TRANSFER_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'JF_TRANSFER_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  // Refunds
  REFUND_TO_FEDERAL_CANDIDATE = 'REFUND_TO_FEDERAL_CANDIDATE',
  REFUND_TO_OTHER_POLITICAL_COMMITTEE = 'REFUND_TO_OTHER_POLITICAL_COMMITTEE',
  REFUND_TO_UNREGISTERED_COMMITTEE = 'REFUND_TO_UNREGISTERED_COMMITTEE',
  // Other
  OFFSET_TO_OPERATING_EXPENDITURES = 'OFFSET_TO_OPERATING_EXPENDITURES',
  OTHER_RECEIPTS = 'OTHER_RECEIPT',
  INDIVIDUAL_RECEIPT_NON_CONTRIBUTION_ACCOUNT = 'INDIVIDUAL_RECEIPT_NON_CONTRIBUTION_ACCOUNT',
  OTHER_COMMITTEE_RECEIPT_NON_CONTRIBUTION_ACCOUNT = 'OTHER_COMMITTEE_NON_CONTRIBUTION_ACCOUNT',
  BUSINESS_LABOR_NON_CONTRIBUTION_ACCOUNT = 'BUSINESS_LABOR_NON_CONTRIBUTION_ACCOUNT',
  INDIVIDUAL_RECOUNT_RECEIPT = 'INDIVIDUAL_RECOUNT_RECEIPT',
  FEDERAL_COMMITTEE_RECOUNT_DONATION = 'FEDERAL_COMMITTEE_RECOUNT_DONATION',
  UNREGISTERED_RECOUNT_DONATION_FROM_ORGANIZATION = 'UNREGISTERED_RECOUNT_DONATION_FROM_ORGANIZATION',
  PARTY_RECOUNT_RECEIPT = 'PARTY_RECOUNT_RECEIPT',
  PAC_RECOUNT_RECEIPT = 'PAC_RECOUNT_RECEIPT',
  TRIBAL_RECOUNT_RECEIPT = 'TRIBAL_RECOUNT_RECEIPT',
  PARTY_NATIONAL_PARTY_RECOUNT_ACCOUNT = 'PARTY_NATIONAL_PARTY_RECOUNT_ACCOUNT',
  INDIVIDUAL_NATIONAL_PARTY_RECOUNT_ACCOUNT = 'INDIVIDUAL_NATIONAL_PARTY_RECOUNT_ACCOUNT',
  PAC_NATIONAL_PARTY_RECOUNT_ACCOUNT = 'PAC_NATIONAL_PARTY_RECOUNT_ACCOUNT',
  TRIBAL_NATIONAL_PARTY_RECOUNT_ACCOUNT = 'TRIBAL_NATIONAL_PARTY_RECOUNT_ACCOUNT',
  INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  PARTY_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'PARTY_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  PAC_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'PAC_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  TRIBAL_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'TRIBAL_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  PAC_NATIONAL_PARTY_CONVENTION_ACCOUNT = 'PAC_NATIONAL_PARTY_CONVENTION_ACCOUNT',
  INDIVIDUAL_NATIONAL_PARTY_CONVENTION_ACCOUNT = 'INDIVIDUAL_NATIONAL_PARTY_CONVENTION_ACCOUNT',
  PARTY_NATIONAL_PARTY_CONVENTION_ACCOUNT = 'PARTY_NATIONAL_PARTY_CONVENTION_ACCOUNT',
  TRIBAL_NATIONAL_PARTY_CONVENTION_ACCOUNT = 'TRIBAL_NATIONAL_PARTY_CONVENTION_ACCOUNT',
  EARMARK_RECEIPT_FOR_RECOUNT_ACCOUNT_CONTRIBUTION = 'EARMARK_RECEIPT_RECOUNT_ACCOUNT',
  EARMARK_RECEIPT_FOR_CONVENTION_ACCOUNT_CONTRIBUTION = 'EARMARK_RECEIPT_CONVENTION_ACCOUNT',
  EARMARK_RECEIPT_FOR_HEADQUARTERS_ACCOUNT_CONTRIBUTION = 'EARMARK_RECEIPT_HEADQUARTERS_ACCOUNT',
  PARTNERSHIP_NATIONAL_PARTY_RECOUNT_ACCOUNT = 'PARTNERSHIP_NATIONAL_PARTY_RECOUNT_ACCOUNT',
  PARTNERSHIP_NATIONAL_PARTY_CONVENTION_ACCOUNT = 'PARTNERSHIP_NATIONAL_PARTY_CONVENTION_ACCOUNT',
  PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT = 'PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT',
  // Child transactiion types
  PAC_EARMARK_MEMO = 'PAC_EARMARK_MEMO',
  EARMARK_MEMO = 'EARMARK_MEMO',
  PAC_JF_TRANSFER_MEMO = 'PAC_JF_TRANSFER_MEMO',
  INDIVIDUAL_JF_TRANSFER_MEMO = 'INDIVIDUAL_JF_TRANSFER_MEMO',
  PARTY_JF_TRANSFER_MEMO = 'PARTY_JF_TRANSFER_MEMO',
  TRIBAL_JF_TRANSFER_MEMO = 'TRIBAL_JF_TRANSFER_MEMO',
  PARTNERSHIP_JF_TRANSFER_MEMO = 'PARTNERSHIP_JF_TRANSFER_MEMO',
  PARTNERSHIP_ATTRIBUTION_JF_TRANSFER_MEMO = 'PARTNERSHIP_ATTRIBUTION_JF_TRANSFER_MEMO',
  PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO = 'PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO',
  INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO = 'INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO',
  PAC_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO = 'PAC_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO',
  TRIBAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO = 'TRIBAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO',
  INDIVIDUAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO = 'INDIVIDUAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO',
  PAC_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO = 'PAC_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO',
  TRIBAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO = 'TRIBAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO',
  INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO = 'INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO',
  PAC_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO = 'PAC_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO',
  TRIBAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO = 'TRIBAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO',
  PARTNERSHIP_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO = 'PARTNERSHIP_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO',
  PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO = 'PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO',
  PARTNERSHIP_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO = 'PARTNERSHIP_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO',
  PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_ACCOUNT_MEMO = 'PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_ACCOUNT_MEMO',
  PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_ACCOUNT_MEMO = 'PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_ACCOUNT_MEMO',
  PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_MEMO = 'PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_MEMO',
  PARTNERSHIP_ATTRIBUTION = 'PARTNERSHIP_ATTRIBUTION',
  PARTNERSHIP_ATTRIBUTION_RECOUNT_ACCOUNT_RECEIPT_MEMO = 'PARTNERSHIP_ATTRIBUTION_RECOUNT_ACCOUNT_RECEIPT_MEMO',
  EARMARK_MEMO_HEADQUARTERS_ACCOUNT = 'EARMARK_MEMO_HEADQUARTERS_ACCOUNT',
  EARMARK_MEMO_CONVENTION_ACCOUNT = 'EARMARK_MEMO_CONVENTION_ACCOUNT',
  EARMARK_MEMO_RECOUNT_ACCOUNT = 'EARMARK_MEMO_RECOUNT_ACCOUNT',
  PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO = 'PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO',
  PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO = 'PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO',
  LOAN_RECEIVED_FROM_INDIVIDUAL_RECEIPT = 'LOAN_RECEIVED_FROM_INDIVIDUAL_RECEIPT',
  LOAN_RECEIVED_FROM_BANK_RECEIPT = 'LOAN_RECEIVED_FROM_BANK_RECEIPT',
  LOAN_REPAYMENT_RECEIVED = 'LOAN_REPAYMENT_RECEIVED',
}

export const ScheduleATransactionTypeLabels: LabelList = [
  // Contributions from Individuals/Persons
  [ScheduleATransactionTypes.INDIVIDUAL_RECEIPT, 'Individual Receipt'],
  [ScheduleATransactionTypes.TRIBAL_RECEIPT, 'Tribal Receipt'],
  [ScheduleATransactionTypes.PARTNERSHIP_RECEIPT, 'Partnership Receipt'],
  [ScheduleATransactionTypes.IN_KIND_RECEIPT, 'In-kind Receipt'],
  [ScheduleATransactionTypes.RETURNED_BOUNCED_RECEIPT_INDIVIDUAL, 'Returned/Bounced Receipt'],
  [ScheduleATransactionTypes.EARMARK_RECEIPT, 'Earmark Receipt'],
  [ScheduleATransactionTypes.EARMARK_MEMO, 'Earmark Memo'],
  [ScheduleATransactionTypes.CONDUIT_EARMARK_RECEIPT, 'Conduit Earmark Receipt'],
  [ScheduleATransactionTypes.CONDUIT_EARMARK_RECEIPT_DEPOSITED, 'Conduit Earmark (Deposited)'],
  [ScheduleATransactionTypes.CONDUIT_EARMARK_RECEIPT_UNDEPOSITED, 'Conduit Earmark (Undeposited)'],
  [ScheduleATransactionTypes.RECEIPT_FROM_UNREGISTERED_ENTITY, 'Receipt from Unregistered Entity'],
  [
    ScheduleATransactionTypes.RECEIPT_FROM_UNREGISTERED_ENTITY_RETURN,
    'Receipt from Unregistered Entity - Returned/Bounced Receipt',
  ],
  // Contributions from Registered Filers
  [ScheduleATransactionTypes.PARTY_RECEIPT, 'Party Receipt'],
  [ScheduleATransactionTypes.PARTY_IN_KIND_RECEIPT, 'Party In-kind Receipt'],
  [ScheduleATransactionTypes.PARTY_RETURN, 'Party Returned/Bounced Receipt'],
  [ScheduleATransactionTypes.PAC_RECEIPT, 'PAC Receipt'],
  [ScheduleATransactionTypes.PAC_IN_KIND_RECEIPT, 'PAC In-kind Receipt'],
  [ScheduleATransactionTypes.PAC_EARMARK_RECEIPT, 'PAC Earmark Receipt'],
  [ScheduleATransactionTypes.PAC_EARMARK_MEMO, 'PAC Earmark Memo'],
  [ScheduleATransactionTypes.PAC_CONDUIT_EARMARK, 'PAC Conduit Earmark'],
  [ScheduleATransactionTypes.PAC_CONDUIT_EARMARK_RECEIPT_DEPOSITED, 'PAC Conduit Earmark (Deposited)'],
  [ScheduleATransactionTypes.PAC_CONDUIT_EARMARK_RECEIPT_UNDEPOSITED, 'PAC Conduit Earmark (Undeposited)'],
  [ScheduleATransactionTypes.PAC_RETURN, 'PAC Returned/Bounced Receipt'],
  [ScheduleATransactionTypes.CONTRIBUTION_FROM_CANDIDATE, 'Contribution from Candidate'],
  [ScheduleATransactionTypes.IN_KIND_CONTRIBUTION_FROM_CANDIDATE, 'In-Kind Contribution from Candidate'],
  // Transfers
  [ScheduleATransactionTypes.TRANSFER, 'Transfer'],
  [ScheduleATransactionTypes.AUTHORIZED_COMMITTEE_TRANSFER, 'Authorized Committee Transfer'],
  [ScheduleATransactionTypes.JOINT_FUNDRAISING_TRANSFER, 'Joint Fundraising Transfer'],
  [ScheduleATransactionTypes.INDIVIDUAL_JF_TRANSFER_MEMO, 'Individual Joint Fundraising Transfer Memo'],
  [ScheduleATransactionTypes.PAC_JF_TRANSFER_MEMO, 'PAC Joint Fundraising Transfer Memo'],
  [ScheduleATransactionTypes.PARTY_JF_TRANSFER_MEMO, 'Party Joint Fundraising Transfer Memo'],
  [ScheduleATransactionTypes.TRIBAL_JF_TRANSFER_MEMO, 'Tribal Joint Fundraising Transfer Memo'],
  [ScheduleATransactionTypes.IN_KIND_TRANSFER, 'In-kind Transfer'],
  [
    ScheduleATransactionTypes.IN_KIND_TRANSFER_FEDERAL_ELECTION_ACTIVITY,
    'In-kind Transfer - Federal Election Activity',
  ],
  [
    ScheduleATransactionTypes.JF_TRANSFER_NATIONAL_PARTY_RECOUNT_ACCOUNT,
    'Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account',
  ],
  [
    ScheduleATransactionTypes.JF_TRANSFER_NATIONAL_PARTY_CONVENTION_ACCOUNT,
    'Joint Fundraising Transfer - National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleATransactionTypes.JF_TRANSFER_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT,
    'Joint Fundraising Transfer - National Party Headquarters Buildings Account',
  ],
  [
    ScheduleATransactionTypes.INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO,
    'Individual National Party Pres. Nominating Convention Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PAC_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO,
    'PAC National Party Pres. Nominating Convention Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.TRIBAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO,
    'Tribal National Party Pres. Nominating Convention Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO,
    'Partnership Receipt Pres. Nominating Convention Account JF Transfer Memo',
  ],
  // Refunds
  [ScheduleATransactionTypes.REFUND_TO_FEDERAL_CANDIDATE, 'Refund of Contribution to Federal Candidate'],
  [
    ScheduleATransactionTypes.REFUND_TO_OTHER_POLITICAL_COMMITTEE,
    'Refund of Contribution to Other Political Committee',
  ],
  [ScheduleATransactionTypes.REFUND_TO_UNREGISTERED_COMMITTEE, 'Refund of Contribution to Unregistered Committee'],
  // Other
  [ScheduleATransactionTypes.OFFSET_TO_OPERATING_EXPENDITURES, 'Offsets to Operating Expenditures'],
  [ScheduleATransactionTypes.OTHER_RECEIPTS, 'Other Receipts'],
  [
    ScheduleATransactionTypes.INDIVIDUAL_RECEIPT_NON_CONTRIBUTION_ACCOUNT,
    'Individual Receipt - Non-contribution Account',
  ],
  [
    ScheduleATransactionTypes.OTHER_COMMITTEE_RECEIPT_NON_CONTRIBUTION_ACCOUNT,
    'Other Committee Receipt - Non-contribution Account',
  ],
  [
    ScheduleATransactionTypes.BUSINESS_LABOR_NON_CONTRIBUTION_ACCOUNT,
    'Business/Labor Organization Receipt - Non-contribution Account',
  ],
  [ScheduleATransactionTypes.INDIVIDUAL_RECOUNT_RECEIPT, 'Individual Recount Receipt'],
  [ScheduleATransactionTypes.PARTY_RECOUNT_RECEIPT, 'Party Recount Receipt'],
  [ScheduleATransactionTypes.PAC_RECOUNT_RECEIPT, 'PAC Recount Receipt'],
  [ScheduleATransactionTypes.TRIBAL_RECOUNT_RECEIPT, 'Tribal Recount Receipt'],
  [ScheduleATransactionTypes.FEDERAL_COMMITTEE_RECOUNT_DONATION, 'Federal Committee Recount Donation'],
  [
    ScheduleATransactionTypes.UNREGISTERED_RECOUNT_DONATION_FROM_ORGANIZATION,
    'Unregistered Recount Donation from Organization',
  ],
  [
    ScheduleATransactionTypes.INDIVIDUAL_NATIONAL_PARTY_RECOUNT_ACCOUNT,
    'Individual National Party Recount/Legal Proceedings Account',
  ],
  [
    ScheduleATransactionTypes.PARTY_NATIONAL_PARTY_RECOUNT_ACCOUNT,
    'Party National Party Recount/Legal Proceedings Account',
  ],
  [
    ScheduleATransactionTypes.PAC_NATIONAL_PARTY_RECOUNT_ACCOUNT,
    'PAC National Party Recount/Legal Proceedings Account',
  ],
  [
    ScheduleATransactionTypes.TRIBAL_NATIONAL_PARTY_RECOUNT_ACCOUNT,
    'Tribal National Party Recount/Legal Proceedings Account',
  ],
  [
    ScheduleATransactionTypes.INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT,
    'Individual National Party Headquarters Buildings Account',
  ],
  [
    ScheduleATransactionTypes.PARTY_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT,
    'Party National Party Headquarters Buildings Account',
  ],
  [
    ScheduleATransactionTypes.PAC_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT,
    'PAC National Party Headquarters Buildings Account',
  ],
  [
    ScheduleATransactionTypes.TRIBAL_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT,
    'Tribal National Party Headquarters Buildings Account',
  ],
  [
    ScheduleATransactionTypes.INDIVIDUAL_NATIONAL_PARTY_CONVENTION_ACCOUNT,
    'Individual National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleATransactionTypes.PARTY_NATIONAL_PARTY_CONVENTION_ACCOUNT,
    'Party National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleATransactionTypes.PAC_NATIONAL_PARTY_CONVENTION_ACCOUNT,
    'PAC National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleATransactionTypes.TRIBAL_NATIONAL_PARTY_CONVENTION_ACCOUNT,
    'Tribal National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleATransactionTypes.EARMARK_RECEIPT_FOR_RECOUNT_ACCOUNT_CONTRIBUTION,
    'Earmark Receipt for Recount/Legal Proceedings Account (Contribution)',
  ],
  [
    ScheduleATransactionTypes.EARMARK_RECEIPT_FOR_CONVENTION_ACCOUNT_CONTRIBUTION,
    'Earmark Receipt for Pres. Nominating Convention Account (Contribution)',
  ],
  [
    ScheduleATransactionTypes.EARMARK_RECEIPT_FOR_HEADQUARTERS_ACCOUNT_CONTRIBUTION,
    'Earmark Receipt for Headquarters Buildings Account (Contribution)',
  ],
  [
    ScheduleATransactionTypes.EARMARK_MEMO_RECOUNT_ACCOUNT,
    'Earmark Memo for Recount/Legal Proceedings Account (Contribution)',
  ],
  [
    ScheduleATransactionTypes.EARMARK_MEMO_CONVENTION_ACCOUNT,
    'Earmark Memo for Pres. Nominating Convention Account (Contribution)',
  ],
  [
    ScheduleATransactionTypes.EARMARK_MEMO_HEADQUARTERS_ACCOUNT,
    'Earmark Memo for Headquarters Buildings Account (Contribution)',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_RECOUNT_ACCOUNT,
    'Partnership National Party Recount/Legal Proceedings Account',
  ],
  [ScheduleATransactionTypes.PARTNERSHIP_RECOUNT_ACCOUNT_RECEIPT, 'Partnership Recount Account Receipt'],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT,
    'Partnership National Party Headquarters Buildings Account',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_CONVENTION_ACCOUNT,
    'Partnership National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleATransactionTypes.INDIVIDUAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO,
    'Individual National Party Recount/Legal Proceedings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PAC_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO,
    'PAC National Party Recount/Legal Proceedings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.TRIBAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO,
    'Tribal National Party Recount/Legal Proceedings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO,
    'Individual National Party Headquarters Buildings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PAC_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO,
    'PAC National Party Headquarters Buildings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.TRIBAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO,
    'Tribal National Party Headquarters Buildings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO,
    'Partnership Receipt Headquarters Buildings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO,
    'Partnership Receipt Recount/Legal Proceedings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO,
    'Partnership National Party Pres. Nominating Convention Proceedings Account Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_ACCOUNT_MEMO,
    'Partnership Attribution National Party Recount/Legal Proceedings Account Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_ACCOUNT_MEMO,
    'Partnership Attribution National Party Pres. Nominating Convention Account Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_MEMO,
    'Partnership Attribution National Party Headquarters Buildings Account Memo',
  ],
  [ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION, 'Partnership Attribution'],
  [ScheduleATransactionTypes.PARTNERSHIP_JF_TRANSFER_MEMO, 'Partnership Receipt Joint Fundraising Transfer Memo'],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_JF_TRANSFER_MEMO,
    'Partnership Attribution Joint Fundraising Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO,
    'Partnership Attribution Pres. Nominating Convention Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_RECOUNT_ACCOUNT_RECEIPT_MEMO,
    'Partnership Attribution Recount Account Receipt Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO,
    'Partnership Attribution Recount/Legal Proceedings Account JF Transfer Memo',
  ],
  [
    ScheduleATransactionTypes.PARTNERSHIP_ATTRIBUTION_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO,
    'Partnership Attribution Headquarters Buildings Account JF Transfer Memo',
  ],
  [ScheduleATransactionTypes.LOAN_RECEIVED_FROM_INDIVIDUAL_RECEIPT, 'Loan Received from Individual'],
  [ScheduleATransactionTypes.LOAN_RECEIVED_FROM_BANK_RECEIPT, 'Loan Received from Bank'],
  [ScheduleATransactionTypes.LOAN_REPAYMENT_RECEIVED, 'Loan Repayment Received'],
];

export const UnimplementedTypeEntityCategories: LabelList = [
  [ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO, 'Partnership'],
  [ScheduleATransactionTypes.PARTNERSHIP_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO, 'Partnership'],
];

// Schedule B
export enum ScheduleBTransactionTypes {
  IN_KIND_OUT = 'IN_KIND_OUT',
  IN_KIND_CONTRIBUTION_TO_CANDIDATE = 'IN_KIND_CONTRIBUTION_TO_CANDIDATE',
  IN_KIND_CONTRIBUTION_TO_OTHER_COMMITTEE = 'IN_KIND_CONTRIBUTION_TO_OTHER_COMMITTEE',
  BUSINESS_LABOR_REFUND_NON_CONTRIBUTION_ACCOUNT = 'BUSINESS_LABOR_REFUND_NON_CONTRIBUTION_ACCOUNT',
  OPERATING_EXPENDITURE = 'OPERATING_EXPENDITURE',
  OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT = 'OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT',
  OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO = 'OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO',
  OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT = 'OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT',
  OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO = 'OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO',
  OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL = 'OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL',
  OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO = 'OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO',
  OPERATING_EXPENDITURE_VOID = 'OPERATING_EXPENDITURE_VOID',
  TRANSFER_TO_AFFILIATES = 'TRANSFER_TO_AFFILIATES',
  CONTRIBUTION_TO_CANDIDATE = 'CONTRIBUTION_TO_CANDIDATE',
  CONTRIBUTION_TO_CANDIDATE_VOID = 'CONTRIBUTION_TO_CANDIDATE_VOID',
  CONTRIBUTION_TO_OTHER_COMMITTEE = 'CONTRIBUTION_TO_OTHER_COMMITTEE',
  CONTRIBUTION_TO_OTHER_COMMITTEE_VOID = 'CONTRIBUTION_TO_OTHER_COMMITTEE_VOID',
  INDIVIDUAL_REFUND_NON_CONTRIBUTION_ACCOUNT = 'INDIVIDUAL_REFUND_NON_CONTRIBUTION_ACCOUNT',
  INDIVIDUAL_REFUND_NP_HEADQUARTERS_ACCOUNT = 'INDIVIDUAL_REFUND_NP_HEADQUARTERS_ACCOUNT',
  INDIVIDUAL_REFUND_NP_CONVENTION_ACCOUNT = 'INDIVIDUAL_REFUND_NP_CONVENTION_ACCOUNT',
  INDIVIDUAL_REFUND_NP_RECOUNT_ACCOUNT = 'INDIVIDUAL_REFUND_NP_RECOUNT_ACCOUNT',
  OTHER_COMMITTEE_REFUND_NON_CONTRIBUTION_ACCOUNT = 'OTHER_COMMITTEE_REFUND_NON_CONTRIBUTION_ACCOUNT',
  OTHER_DISBURSEMENT = 'OTHER_DISBURSEMENT',
  OTHER_DISBURSEMENT_CREDIT_CARD_PAYMENT = 'OTHER_DISBURSEMENT_CREDIT_CARD_PAYMENT',
  OTHER_DISBURSEMENT_CREDIT_CARD_PAYMENT_MEMO = 'OTHER_DISBURSEMENT_CREDIT_CARD_PAYMENT_MEMO',
  OTHER_DISBURSEMENT_STAFF_REIMBURSEMENT = 'OTHER_DISBURSEMENT_STAFF_REIMBURSEMENT',
  OTHER_DISBURSEMENT_STAFF_REIMBURSEMENT_MEMO = 'OTHER_DISBURSEMENT_STAFF_REIMBURSEMENT_MEMO',
  OTHER_DISBURSEMENT_PAYMENT_TO_PAYROLL = 'OTHER_DISBURSEMENT_PAYMENT_TO_PAYROLL',
  OTHER_DISBURSEMENT_PAYMENT_TO_PAYROLL_MEMO = 'OTHER_DISBURSEMENT_PAYMENT_TO_PAYROLL_MEMO',
  OTHER_DISBURSEMENT_VOID = 'OTHER_DISBURSEMENT_VOID',
  NON_CONTRIBUTION_ACCOUNT_DISBURSEMENT = 'NON_CONTRIBUTION_ACCOUNT_DISBURSEMENT',
  NON_CONTRIBUTION_ACCOUNT_CREDIT_CARD_PAYMENT = 'NON_CONTRIBUTION_ACCOUNT_CREDIT_CARD_PAYMENT',
  NON_CONTRIBUTION_ACCOUNT_CREDIT_CARD_PAYMENT_MEMO = 'NON_CONTRIBUTION_ACCOUNT_CREDIT_CARD_PAYMENT_MEMO',
  NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT = 'NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT',
  NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT_MEMO = 'NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT_MEMO',
  NON_CONTRIBUTION_ACCOUNT_PAYMENT_TO_PAYROLL = 'NON_CONTRIBUTION_ACCOUNT_PAYMENT_TO_PAYROLL',
  NON_CONTRIBUTION_ACCOUNT_PAYMENT_TO_PAYROLL_MEMO = 'NON_CONTRIBUTION_ACCOUNT_PAYMENT_TO_PAYROLL_MEMO',
  NATIONAL_PARTY_RECOUNT_ACCOUNT_DISBURSEMENT = 'NATIONAL_PARTY_RECOUNT_ACCOUNT_DISBURSEMENT',
  RECOUNT_ACCOUNT_DISBURSEMENT = 'RECOUNT_ACCOUNT_DISBURSEMENT',
  NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_DISBURSEMENT = 'NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_DISBURSEMENT',
  NATIONAL_PARTY_CONVENTION_ACCOUNT_DISBURSEMENT = 'NATIONAL_PARTY_CONVENTION_ACCOUNT_DISBURSEMENT',
  TRIBAL_REFUND_NP_HEADQUARTERS_ACCOUNT = 'TRIBAL_REFUND_NP_HEADQUARTERS_ACCOUNT',
  TRIBAL_REFUND_NP_CONVENTION_ACCOUNT = 'TRIBAL_REFUND_NP_CONVENTION_ACCOUNT',
  TRIBAL_REFUND_NP_RECOUNT_ACCOUNT = 'TRIBAL_REFUND_NP_RECOUNT_ACCOUNT',
  REFUND_INDIVIDUAL_CONTRIBUTION = 'REFUND_INDIVIDUAL_CONTRIBUTION',
  REFUND_INDIVIDUAL_CONTRIBUTION_VOID = 'REFUND_INDIVIDUAL_CONTRIBUTION_VOID',
  REFUND_PARTY_CONTRIBUTION = 'REFUND_PARTY_CONTRIBUTION',
  REFUND_PARTY_CONTRIBUTION_VOID = 'REFUND_PARTY_CONTRIBUTION_VOID',
  REFUND_PAC_CONTRIBUTION = 'REFUND_PAC_CONTRIBUTION',
  REFUND_PAC_CONTRIBUTION_VOID = 'REFUND_PAC_CONTRIBUTION_VOID',
  REFUND_UNREGISTERED_CONTRIBUTION = 'REFUND_UNREGISTERED_CONTRIBUTION',
  REFUND_UNREGISTERED_CONTRIBUTION_VOID = 'REFUND_UNREGISTERED_CONTRIBUTION_VOID',
  FEDERAL_ELECTION_ACTIVITY_100PCT_PAYMENT = 'FEDERAL_ELECTION_ACTIVITY_100PCT_PAYMENT',
  FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT = 'FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT',
  FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT_MEMO = 'FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT_MEMO',
  FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT = 'FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT',
  FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT_MEMO = 'FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT_MEMO',
  FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL = 'FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL',
  FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL_MEMO = 'FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL_MEMO',
  FEDERAL_ELECTION_ACTIVITY_VOID = 'FEDERAL_ELECTION_ACTIVITY_VOID',
  OTHER_COMMITTEE_REFUND_REFUND_NP_HEADQUARTERS_ACCOUNT = 'OTHER_COMMITTEE_REFUND_REFUND_NP_HEADQUARTERS_ACCOUNT',
  OTHER_COMMITTEE_REFUND_REFUND_NP_CONVENTION_ACCOUNT = 'OTHER_COMMITTEE_REFUND_REFUND_NP_CONVENTION_ACCOUNT',
  OTHER_COMMITTEE_REFUND_REFUND_NP_RECOUNT_ACCOUNT = 'OTHER_COMMITTEE_REFUND_REFUND_NP_RECOUNT_ACCOUNT',
  PARTY_IN_KIND_OUT = 'PARTY_IN_KIND_OUT',
  IN_KIND_TRANSFER_OUT = 'IN_KIND_TRANSFER_OUT',
  IN_KIND_TRANSFER_FEA_OUT = 'IN_KIND_TRANSFER_FEA_OUT',
  PAC_IN_KIND_OUT = 'PAC_IN_KIND_OUT',
  PAC_CONDUIT_EARMARK_OUT = 'PAC_CONDUIT_EARMARK_OUT',
  PAC_CONDUIT_EARMARK_OUT_DEPOSITED = 'PAC_CONDUIT_EARMARK_OUT_DEPOSITED',
  PAC_CONDUIT_EARMARK_OUT_UNDEPOSITED = 'PAC_CONDUIT_EARMARK_OUT_UNDEPOSITED',
  CONDUIT_EARMARK_OUT = 'CONDUIT_EARMARK_OUT',
  CONDUIT_EARMARK_OUT_DEPOSITED = 'CONDUIT_EARMARK_OUT_DEPOSITED',
  CONDUIT_EARMARK_OUT_UNDEPOSITED = 'CONDUIT_EARMARK_OUT_UNDEPOSITED',
  LOAN_MADE = 'LOAN_MADE',
  LOAN_REPAYMENT_MADE = 'LOAN_REPAYMENT_MADE',
  OTHER_FEDERAL_CANDIDATE_CONTRIBUTION = 'OTHER_FEDERAL_CANDIDATE_CONTRIBUTION',
  OTHER_FEDERAL_COMMITTEE_CONTRIBUTION = 'OTHER_FEDERAL_COMMITTEE_CONTRIBUTION',
  UNREGISTERED_ORGANIZATION_CONTRIBUTION = 'UNREGISTERED_ORGANIZATION_CONTRIBUTION',
  DISGORGEMENT = 'DISGORGEMENT',
  REFUND_UNREGISTERED_RECEIPT_ORGANIZATION = 'REFUND_UNREGISTERED_RECEIPT_ORGANIZATION',
  REFUND_UNREGISTERED_RECEIPT_ORGANIZATION_VOID = 'REFUND_UNREGISTERED_RECEIPT_ORGANIZATION_VOID',
  REFUND_FEDERAL_COMMITTEE_CONTRIBUTION = 'REFUND_FEDERAL_COMMITTEE_CONTRIBUTION',
  REFUND_FEDERAL_COMMITTEE_CONTRIBUTION_VOID = 'REFUND_FEDERAL_COMMITTEE_CONTRIBUTION_VOID',
}

export const ScheduleBTransactionTypeLabels: LabelList = [
  [ScheduleBTransactionTypes.IN_KIND_OUT, 'In-kind Out'],
  [ScheduleBTransactionTypes.IN_KIND_CONTRIBUTION_TO_CANDIDATE, 'In-kind Contribution to Candidate'],
  [ScheduleBTransactionTypes.IN_KIND_CONTRIBUTION_TO_OTHER_COMMITTEE, 'In-kind Contribution to Other Committee'],
  [
    ScheduleBTransactionTypes.BUSINESS_LABOR_REFUND_NON_CONTRIBUTION_ACCOUNT,
    'Business/Labor Organization Refund - Non-contribution Account',
  ],
  [ScheduleBTransactionTypes.OPERATING_EXPENDITURE, 'Operating Expenditure'],
  [
    ScheduleBTransactionTypes.OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT,
    'Credit Card Payment for Operating Expenditure',
  ],
  [
    ScheduleBTransactionTypes.OPERATING_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO,
    'Credit Card Memo for Operating Expenditure',
  ],
  [
    ScheduleBTransactionTypes.OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT,
    'Staff Reimbursement for Operating Expenditure',
  ],
  [
    ScheduleBTransactionTypes.OPERATING_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO,
    'Staff Reimbursement Memo for Operating Expenditure',
  ],
  [ScheduleBTransactionTypes.OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL, 'Payment to Payroll for Operating Expenditure'],
  [ScheduleBTransactionTypes.OPERATING_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO, 'Payroll Memo for Operating Expenditure'],
  [ScheduleBTransactionTypes.OPERATING_EXPENDITURE_VOID, 'Operating Expenditure - Void'],
  [ScheduleBTransactionTypes.TRANSFER_TO_AFFILIATES, 'Transfers to Affiliates/Other Committees'],
  [ScheduleBTransactionTypes.CONTRIBUTION_TO_CANDIDATE, 'Contribution to Candidate'],
  [ScheduleBTransactionTypes.CONTRIBUTION_TO_CANDIDATE_VOID, 'Contribution to Candidate - Void'],
  [ScheduleBTransactionTypes.CONTRIBUTION_TO_OTHER_COMMITTEE, 'Contribution to Other Committee'],
  [ScheduleBTransactionTypes.CONTRIBUTION_TO_OTHER_COMMITTEE_VOID, 'Contribution to Other Committee - Void'],
  [
    ScheduleBTransactionTypes.INDIVIDUAL_REFUND_NON_CONTRIBUTION_ACCOUNT,
    'Individual Refund - Non-contribution Account',
  ],
  [
    ScheduleBTransactionTypes.INDIVIDUAL_REFUND_NP_HEADQUARTERS_ACCOUNT,
    'Individual Refund - National Party Headquarters Buildings Account',
  ],
  [
    ScheduleBTransactionTypes.INDIVIDUAL_REFUND_NP_CONVENTION_ACCOUNT,
    'Individual Refund - National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleBTransactionTypes.INDIVIDUAL_REFUND_NP_RECOUNT_ACCOUNT,
    'Individual Refund - National Party Recount/Legal Proceedings Account',
  ],
  [
    ScheduleBTransactionTypes.OTHER_COMMITTEE_REFUND_NON_CONTRIBUTION_ACCOUNT,
    'Other Committee Refund - Non-contribution Account',
  ],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT, 'Other Disbursement'],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT_CREDIT_CARD_PAYMENT, 'Credit Card Payment for Other Disbursement'],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT_CREDIT_CARD_PAYMENT_MEMO, 'Credit Card Memo for Other Disbursement'],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT_STAFF_REIMBURSEMENT, 'Staff Reimbursement for Other Disbursement'],
  [
    ScheduleBTransactionTypes.OTHER_DISBURSEMENT_STAFF_REIMBURSEMENT_MEMO,
    'Staff Reimbursement Memo for Other Disbursement',
  ],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT_PAYMENT_TO_PAYROLL, 'Payment to Payroll for Other Disbursement'],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT_PAYMENT_TO_PAYROLL_MEMO, 'Payroll Memo for Other Disbursement'],
  [ScheduleBTransactionTypes.OTHER_DISBURSEMENT_VOID, 'Other Disbursement - Void'],
  [ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_DISBURSEMENT, 'Non-contribution Account Disbursement'],
  [
    ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_CREDIT_CARD_PAYMENT,
    'Non-contribution Account Credit Card Payment',
  ],
  [
    ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_CREDIT_CARD_PAYMENT_MEMO,
    'Non-contribution Account Credit Card Payment Memo',
  ],
  [
    ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT,
    'Non-contribution Account Staff Reimbursement',
  ],
  [
    ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT_MEMO,
    'Non-contribution Account Staff Reimbursement Memo',
  ],
  [
    ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_PAYMENT_TO_PAYROLL,
    'Non-contribution Account Payment to Payroll',
  ],
  [
    ScheduleBTransactionTypes.NON_CONTRIBUTION_ACCOUNT_PAYMENT_TO_PAYROLL_MEMO,
    'Non-contribution Account Payment to Payroll Memo',
  ],
  [
    ScheduleBTransactionTypes.NATIONAL_PARTY_RECOUNT_ACCOUNT_DISBURSEMENT,
    'National Party Recount/Legal Proceedings Account Disbursement',
  ],
  [ScheduleBTransactionTypes.RECOUNT_ACCOUNT_DISBURSEMENT, 'Recount Account Disbursement'],
  [
    ScheduleBTransactionTypes.NATIONAL_PARTY_HEADQUARTERS_ACCOUNT_DISBURSEMENT,
    'National Party Headquarters Buildings Account Disbursement',
  ],
  [
    ScheduleBTransactionTypes.NATIONAL_PARTY_CONVENTION_ACCOUNT_DISBURSEMENT,
    'National Party Pres. Nominating Convention Account Disbursement',
  ],
  [
    ScheduleBTransactionTypes.TRIBAL_REFUND_NP_HEADQUARTERS_ACCOUNT,
    'Tribal Refund - National Party Headquarters Buildings Account',
  ],
  [
    ScheduleBTransactionTypes.TRIBAL_REFUND_NP_CONVENTION_ACCOUNT,
    'Tribal Refund - National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleBTransactionTypes.TRIBAL_REFUND_NP_RECOUNT_ACCOUNT,
    'Tribal Refund - National Party Recount/Legal Proceedings Account',
  ],
  [ScheduleBTransactionTypes.REFUND_INDIVIDUAL_CONTRIBUTION, 'Refund of Individual Contribution'],
  [ScheduleBTransactionTypes.REFUND_INDIVIDUAL_CONTRIBUTION_VOID, 'Refund of Individual Contribution - Void'],
  [ScheduleBTransactionTypes.REFUND_PARTY_CONTRIBUTION, 'Refund of Party Contribution'],
  [ScheduleBTransactionTypes.REFUND_PARTY_CONTRIBUTION_VOID, 'Refund of Party Contribution - Void'],
  [ScheduleBTransactionTypes.REFUND_PAC_CONTRIBUTION, 'Refund of PAC Contribution'],
  [ScheduleBTransactionTypes.REFUND_PAC_CONTRIBUTION_VOID, 'Refund of PAC Contribution - Void'],
  [ScheduleBTransactionTypes.REFUND_UNREGISTERED_CONTRIBUTION, 'Refund of Unregistered Receipt from Person'],
  [
    ScheduleBTransactionTypes.REFUND_UNREGISTERED_CONTRIBUTION_VOID,
    'Refund of Unregistered Receipt from Person - Void',
  ],
  [ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_100PCT_PAYMENT, '100% Federal Election Activity Payment'],
  [
    ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT,
    'Credit Card Payment for 100% Federal Election Activity',
  ],
  [
    ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_CREDIT_CARD_PAYMENT_MEMO,
    'Credit Card Memo for 100% Federal Election Activity',
  ],
  [
    ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT,
    'Staff Reimbursement for 100% Federal Election Activity',
  ],
  [
    ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_STAFF_REIMBURSEMENT_MEMO,
    'Staff Reimbursement Memo for 100% Federal Election Activity',
  ],
  [
    ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL,
    'Payment to Payroll for 100% Federal Election Activity',
  ],
  [
    ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_PAYMENT_TO_PAYROLL_MEMO,
    'Payroll Memo for 100% Federal Election Activity',
  ],
  [ScheduleBTransactionTypes.FEDERAL_ELECTION_ACTIVITY_VOID, '100% Federal Election Activity Payment - Void'],
  [
    ScheduleBTransactionTypes.OTHER_COMMITTEE_REFUND_REFUND_NP_HEADQUARTERS_ACCOUNT,
    'Other Committee Refund - National Party Headquarters Buildings Account',
  ],
  [
    ScheduleBTransactionTypes.OTHER_COMMITTEE_REFUND_REFUND_NP_CONVENTION_ACCOUNT,
    'Other Committee Refund - National Party Pres. Nominating Convention Account',
  ],
  [
    ScheduleBTransactionTypes.OTHER_COMMITTEE_REFUND_REFUND_NP_RECOUNT_ACCOUNT,
    'Other Committee Refund - National Party Recount/Legal Proceedings Account',
  ],
  [ScheduleBTransactionTypes.PARTY_IN_KIND_OUT, 'Party In-kind Out'],
  [ScheduleBTransactionTypes.IN_KIND_TRANSFER_OUT, 'In-kind Transfer Out'],
  [ScheduleBTransactionTypes.IN_KIND_TRANSFER_FEA_OUT, 'In-kind Transfer Federal Election Activity Out'],
  [ScheduleBTransactionTypes.PAC_IN_KIND_OUT, 'PAC In-kind Out'],
  [ScheduleBTransactionTypes.PAC_CONDUIT_EARMARK_OUT, 'PAC Conduit Earmark Out'],
  [ScheduleBTransactionTypes.PAC_CONDUIT_EARMARK_OUT_DEPOSITED, 'PAC Conduit Earmark Out (Deposited)'],
  [ScheduleBTransactionTypes.PAC_CONDUIT_EARMARK_OUT_UNDEPOSITED, 'PAC Conduit Earmark Out (Undeposited)'],
  [ScheduleBTransactionTypes.CONDUIT_EARMARK_OUT, 'Conduit Earmark Out'],
  [ScheduleBTransactionTypes.CONDUIT_EARMARK_OUT_DEPOSITED, 'Conduit Earmark Out (Deposited)'],
  [ScheduleBTransactionTypes.CONDUIT_EARMARK_OUT_UNDEPOSITED, 'Conduit Earmark Out (Undeposited)'],
  [ScheduleBTransactionTypes.LOAN_MADE, 'Loan Made'],
  [ScheduleBTransactionTypes.LOAN_REPAYMENT_MADE, 'Loan Repayment Made'],
  [ScheduleBTransactionTypes.OTHER_FEDERAL_CANDIDATE_CONTRIBUTION, 'Other Federal Candidate Contribution'],
  [ScheduleBTransactionTypes.OTHER_FEDERAL_COMMITTEE_CONTRIBUTION, 'Other Federal Committee Contribution'],
  [ScheduleBTransactionTypes.UNREGISTERED_ORGANIZATION_CONTRIBUTION, 'Unregistered Organization Contribution'],
  [ScheduleBTransactionTypes.DISGORGEMENT, 'Disgorgement'],
  [
    ScheduleBTransactionTypes.REFUND_UNREGISTERED_RECEIPT_ORGANIZATION,
    'Refund of Unregistered Receipt from Organization',
  ],
  [
    ScheduleBTransactionTypes.REFUND_UNREGISTERED_RECEIPT_ORGANIZATION_VOID,
    'Refund of Unregistered Receipt from Organization - Void',
  ],
  [ScheduleBTransactionTypes.REFUND_FEDERAL_COMMITTEE_CONTRIBUTION, 'Refund of Federal Committee Contribution'],
  [
    ScheduleBTransactionTypes.REFUND_FEDERAL_COMMITTEE_CONTRIBUTION_VOID,
    'Refund of Federal Committee Contribution - Void',
  ],
];

// Schedule C
export enum ScheduleCTransactionTypes {
  LOAN_RECEIVED_FROM_INDIVIDUAL = 'LOAN_RECEIVED_FROM_INDIVIDUAL',
  LOAN_RECEIVED_FROM_BANK = 'LOAN_RECEIVED_FROM_BANK',
  LOAN_BY_COMMITTEE = 'LOAN_BY_COMMITTEE',
}

export const ScheduleCTransactionTypeLabels: LabelList = [
  [ScheduleCTransactionTypes.LOAN_RECEIVED_FROM_INDIVIDUAL, 'Loan Received from Individual'],
  [ScheduleCTransactionTypes.LOAN_RECEIVED_FROM_BANK, 'Loan Received from Bank'],
  [ScheduleCTransactionTypes.LOAN_BY_COMMITTEE, 'Loan By Committee'],
];

// Schedule C1
export enum ScheduleC1TransactionTypes {
  C1_LOAN_AGREEMENT = 'C1_LOAN_AGREEMENT',
}

export const ScheduleC1TransactionTypeLabels: LabelList = [
  [ScheduleC1TransactionTypes.C1_LOAN_AGREEMENT, 'Loan Agreement'],
];

// Schedule C2
export enum ScheduleC2TransactionTypes {
  C2_LOAN_GUARANTOR = 'C2_LOAN_GUARANTOR',
}

export const ScheduleC2TransactionTypeLabels: LabelList = [
  [ScheduleC2TransactionTypes.C2_LOAN_GUARANTOR, 'Guarantors to loan source'],
];

// Schedule D
export enum ScheduleDTransactionTypes {
  DEBT_OWED_BY_COMMITTEE = 'DEBT_OWED_BY_COMMITTEE',
  DEBT_OWED_TO_COMMITTEE = 'DEBT_OWED_TO_COMMITTEE',
}

export const ScheduleDTransactionTypeLabels: LabelList = [
  [ScheduleDTransactionTypes.DEBT_OWED_BY_COMMITTEE, 'Debt Owed By Committee'],
  [ScheduleDTransactionTypes.DEBT_OWED_TO_COMMITTEE, 'Debt Owed To Committee'],
];

// Schedule E
export enum ScheduleETransactionTypes {
  INDEPENDENT_EXPENDITURE = 'INDEPENDENT_EXPENDITURE',
  INDEPENDENT_EXPENDITURE_VOID = 'INDEPENDENT_EXPENDITURE_VOID',
  MULTISTATE_INDEPENDENT_EXPENDITURE = 'MULTISTATE_INDEPENDENT_EXPENDITURE',
  INDEPENDENT_EXPENDITURE_DEBT = 'INDEPENDENT_EXPENDITURE_DEBT',
  INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT = 'INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT',
  INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO = 'INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO',
  INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT = 'INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT',
  INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO = 'INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO',
  INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL = 'INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL',
  INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO = 'INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO',
}

export const ScheduleETransactionTypeLabels: LabelList = [
  [ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE, 'Independent Expenditure'],
  [ScheduleETransactionTypes.MULTISTATE_INDEPENDENT_EXPENDITURE, 'Multistate Independent Expenditure'],
  [ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_DEBT, 'Debt for Independent Expenditure'],
  [
    ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT,
    'Credit Card Payment for Independent Expenditure',
  ],
  [
    ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_CREDIT_CARD_PAYMENT_MEMO,
    'Credit Card Memo for Independent Expenditure',
  ],
  [
    ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT,
    'Staff Reimbursement for Independent Expenditure',
  ],
  [
    ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_STAFF_REIMBURSEMENT_MEMO,
    'Staff Reimbursement Memo for Independent Expenditure',
  ],
  [
    ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL,
    'Payment to Payroll for Independent Expenditure',
  ],
  [
    ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_PAYMENT_TO_PAYROLL_MEMO,
    'Payroll Memo for Independent Expenditure',
  ],
  [ScheduleETransactionTypes.INDEPENDENT_EXPENDITURE_VOID, 'Independent Expenditure - Void'],
];

// Schedule F
export enum ScheduleFTransactionTypes {
  COORDINATED_PARTY_EXPENDITURE = 'COORDINATED_PARTY_EXPENDITURE',
  COORDINATED_PARTY_EXPENDITURE_VOID = 'COORDINATED_PARTY_EXPENDITURE_VOID',
}

export const ScheduleFTransactionTypeLabels: LabelList = [
  [ScheduleFTransactionTypes.COORDINATED_PARTY_EXPENDITURE, 'Coordinated Party Expenditure'],
  [ScheduleFTransactionTypes.COORDINATED_PARTY_EXPENDITURE_VOID, 'Void of Coordinated Party Expenditure'],
];

export type TransactionTypes =
  | ScheduleATransactionTypes
  | ScheduleBTransactionTypes
  | ScheduleCTransactionTypes
  | ScheduleC1TransactionTypes
  | ScheduleC2TransactionTypes
  | ScheduleDTransactionTypes
  | ScheduleETransactionTypes
  | ScheduleFTransactionTypes;

  export enum AggregationGroups {
  GENERAL = 'GENERAL',
  LINE_14 = 'LINE_14',
  LINE_15 = 'LINE_15',
  LINE_16 = 'LINE_16',
  NATIONAL_PARTY_CONVENTION_ACCOUNT = 'NATIONAL_PARTY_CONVENTION_ACCOUNT',
  NATIONAL_PARTY_HEADQUARTERS_ACCOUNT = 'NATIONAL_PARTY_HEADQUARTERS_ACCOUNT',
  NATIONAL_PARTY_RECOUNT_ACCOUNT = 'NATIONAL_PARTY_RECOUNT_ACCOUNT',
  NON_CONTRIBUTION_ACCOUNT = 'NON_CONTRIBUTION_ACCOUNT',
  OTHER_RECEIPTS = 'OTHER_RECEIPTS',
  RECOUNT_ACCOUNT = 'RECOUNT_ACCOUNT',
  GENERAL_DISBURSEMENT = 'GENERAL_DISBURSEMENT',
  INDEPENDENT_EXPENDITURE = 'INDEPENDENT_EXPENDITURE',
  COORDINATED_PARTY_EXPENDITURES = 'COORDINATED_PARTY_EXPENDITURES',
}

export enum ScheduleIds {
  A = 'A',
  B = 'B',
  C = 'C',
  C1 = 'C1',
  C2 = 'C2',
  D = 'D',
  E = 'E',
  F = 'F',
}
