import { PrimeOptions } from 'app/shared/utils/label.utils';
import { TransactionTemplateMapType } from '../transaction-type.model';

export abstract class DoubleTransactionGroup {
  abstract getFormProperties(templateMap: TransactionTemplateMapType): string[];
  abstract getChildFormProperties(childTemplateMap: TransactionTemplateMapType): string[];

  abstract getContactTypeOptions(): PrimeOptions;
  abstract getChildContactTypeOptions(): PrimeOptions;

  abstract hasEmployerInput(): boolean;
  abstract childHasEmployerInput(): boolean;

  abstract getParentTransactionTitle(): string;
  abstract getParentFooter(): string;
  abstract getChildTransactionTitle(): string;
  abstract getChildTransactionSubTitle(): string;
  abstract getGroupDescription(): string;

  abstract getParentAccordionTitle(): string;
  abstract getParentAccordionSubTitle(): string;
  abstract getChildAccordionTitle(): string;
  abstract getChildAccordionSubTitle(): string;

  abstract getChildContactLabel(): string;

  abstract getAutoGeneratedChildFields(childTemplateMap: TransactionTemplateMapType): string[];
}
