import { TestBed } from '@angular/core/testing';
import { LabelUtils } from 'app/shared/utils/label.utils';
import { testTemplateMap } from 'app/shared/utils/unit-test.utils';
import { ContactTypeLabels, ContactTypes } from '../contact.model';
import { TransactionGroupEE } from './transaction-group-ee.model';

describe('TransactionGroupEE', () => {
  let component: TransactionGroupEE;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [],
      providers: [TransactionGroupEE],
    });

    component = TestBed.inject(TransactionGroupEE);
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('#getFormProperties should include organization name', () => {
    const testOrgName = 'org name';
    const testTemplateMapCopy = { ...testTemplateMap };
    testTemplateMapCopy.organization_name = testOrgName;
    const retval = component.getFormProperties(testTemplateMapCopy);
    expect(retval.includes(testOrgName)).toBeTruthy();
  });

  it('#getChildFormProperties should include organization name', () => {
    const testOrgName = 'org name';
    const testTemplateMapCopy = { ...testTemplateMap };
    testTemplateMapCopy.organization_name = testOrgName;
    const retval = component.getChildFormProperties(testTemplateMapCopy);
    expect(retval.includes(testOrgName)).toBeTruthy();
  });

  it('#getContactTypeOptions should return committee', () => {
    const expectedRetval = LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.COMMITTEE]);
    const retval = component.getContactTypeOptions();
    expect(JSON.stringify(expectedRetval) === JSON.stringify(retval)).toBeTruthy();
  });

  it('#getChildContactTypeOptions should return committee', () => {
    const expectedOptions = LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.COMMITTEE]);
    const options = component.getChildContactTypeOptions();
    expect(JSON.stringify(expectedOptions) === JSON.stringify(options)).toBeTruthy();
  });

  it('#hasEmployerInput should return false', () => {
    const retval = component.hasEmployerInput();
    expect(retval).toBeFalse();
  });

  it('#test group methods to ensure they return the right values', () => {
    expect(component.childHasEmployerInput()).toBeFalse();
    expect(component.getParentTransactionTitle()).toBe('');
    expect(component.getParentFooter()).toBe(
      'The information in this receipt will automatically populate a related transaction. Review the associated disbursement or click "Save both transactions" to record these transactions.'
    );
    expect(component.getGroupDescription()).toBe(
      'This receipt type automatically creates an associated transaction. Saving an in-kind receipt will automatically create an in-kind out.'
    );
    expect(component.getParentAccordionTitle()).toBe('ENTER DATA');
    expect(component.getParentAccordionSubTitle()).toBe('Add contact and receipt information');
    expect(component.getChildAccordionTitle()).toBe('AUTO-POPULATED');
    expect(component.getChildAccordionSubTitle()).toBe('Review disbursement information');
    expect(component.getChildContactLabel()).toBe('Committee');
    expect(component.getAutoGeneratedChildFields(testTemplateMap).length).toBe(14);
    expect(component.getChildTransactionSubTitle()).toBe(
      'To update any errors found, return to the previous step to update the in-kind receipt.'
    );
    expect(component.hasChildCandidateInformationInput()).toBeFalse();
    expect(component.hasChildElectionInformationInput()).toBeFalse();
    expect(component.hasParentCandidateInformationInput()).toBeFalse();
    expect(component.hasParentElectionInformationInput()).toBeFalse();
  });
});
