import { LabelUtils, PrimeOptions } from 'app/shared/utils/label.utils';
import { ContactTypeLabels, ContactTypes } from '../contact.model';
import { TransactionTemplateMapType } from '../transaction-type.model';
import { DoubleTransactionGroup } from './double-transaction-group.model';

export class TransactionGroupYB extends DoubleTransactionGroup {
  getFormProperties(templateMap: TransactionTemplateMapType): string[] {
    return [
      'entity_type',
      templateMap.organization_name,
      templateMap.committee_fec_id,
      templateMap.last_name,
      templateMap.first_name,
      templateMap.middle_name,
      templateMap.prefix,
      templateMap.suffix,
      templateMap.street_1,
      templateMap.street_2,
      templateMap.city,
      templateMap.state,
      templateMap.zip,
      templateMap.amount,
      'loan_payment_to_date',
      templateMap.balance,
      templateMap.memo_code,
      templateMap.date,
      'loan_due_date',
      'loan_interest_rate',
      'secured',
      templateMap.text4000,
    ].filter((field) => !!field);
  }

  getChildFormProperties(childTemplateMap: TransactionTemplateMapType): string[] {
    return [
      'entity_type',
      childTemplateMap.organization_name,
      childTemplateMap.committee_fec_id,
      childTemplateMap.street_1,
      childTemplateMap.street_2,
      childTemplateMap.city,
      childTemplateMap.state,
      childTemplateMap.zip,
      childTemplateMap.date,
      childTemplateMap.amount,
      childTemplateMap.purpose_description,
      childTemplateMap.memo_code,
      childTemplateMap.text4000,
    ].filter((field) => !!field);
  }

  getContactTypeOptions(): PrimeOptions {
    return LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.COMMITTEE]);
  }

  getChildContactTypeOptions(): PrimeOptions {
    return LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.COMMITTEE]);
  }

  hasEmployerInput(): boolean {
    return false;
  }

  override childHasEmployerInput(): boolean {
    return false;
  }

  getParentTransactionTitle(): string {
    return '';
  }

  getParentFooter(): string {
    return 'The information in this loan will automatically populate a related transaction. Review the associated loan and enter a purpose of receipt or note/memo text; or click "Save transactions" to record these transactions.';
  }

  getChildTransactionSubTitle(): string {
    return 'Only the Purpose of Disbursement and Note/Memo Text are editable. To update any errors found, return to <b>ENTER DATA</b> to update loan information.';
  }

  getGroupDescription(): string {
    return 'This loan type automatically creates an associated transaction. Saving a loan by committee will automatically create an associated disbursement.';
  }

  getParentAccordionTitle(): string {
    return 'ENTER DATA';
  }

  getParentAccordionSubTitle(): string {
    return 'Enter lender, loan, and terms information for a loan by committee';
  }

  getChildAccordionTitle(): string {
    return 'AUTO-POPULATED';
  }

  getChildAccordionSubTitle(): string {
    return 'Review information and enter purpose of description or note/memo text for the loan made';
  }

  getChildContactLabel(): string {
    return 'Lendee';
  }

  hasChildCandidateInformationInput(): boolean {
    return false;
  }

  hasChildElectionInformationInput(): boolean {
    return false;
  }

  hasParentCandidateInformationInput(): boolean {
    return false;
  }

  hasParentElectionInformationInput(): boolean {
    return false;
  }

  getAutoGeneratedChildFields(childTemplateMap: TransactionTemplateMapType): string[] {
    return this.getChildFormProperties(childTemplateMap).filter(
      (field) => ![childTemplateMap.text4000, childTemplateMap.category_code].includes(field)
    );
  }
}
