import { TestBed } from '@angular/core/testing';
import { LabelUtils } from 'app/shared/utils/label.utils';
import { testTemplateMap } from 'app/shared/utils/unit-test.utils';
import { ContactTypeLabels, ContactTypes } from '../contact.model';
import { TransactionGroupAG } from './transaction-group-ag.model';

describe('TransactionGroupAG', () => {
  let component: TransactionGroupAG;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [],
      providers: [TransactionGroupAG],
    });

    component = TestBed.inject(TransactionGroupAG);
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('#getFormProperties happy path', () => {
    const testLastName = 'testLastName';
    const testTemplateMapCopy = { ...testTemplateMap };
    testTemplateMapCopy.last_name = testLastName;
    const retval = component.getFormProperties(testTemplateMapCopy);
    expect(retval.includes(testLastName)).toBeTruthy();
  });

  it('#getChildFormProperties happy path', () => {
    const testOrganizationName = 'testOrganizationName';
    const testTemplateMapCopy = { ...testTemplateMap };
    testTemplateMapCopy.organization_name = testOrganizationName;
    const retval = component.getChildFormProperties(testTemplateMapCopy);
    expect(retval.includes(testOrganizationName)).toBeTruthy();
  });

  it('#getContactTypeOptions happy path', () => {
    const expectedRetval = LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.INDIVIDUAL]);
    const retval = component.getContactTypeOptions();
    expect(JSON.stringify(expectedRetval) === JSON.stringify(retval)).toBeTruthy();
  });

  it('#getChildContactTypeOptions happy path', () => {
    const expectedRetval = LabelUtils.getPrimeOptions(ContactTypeLabels, [
      ContactTypes.COMMITTEE,
      ContactTypes.INDIVIDUAL,
    ]);
    const retval = component.getChildContactTypeOptions();
    expect(JSON.stringify(expectedRetval) === JSON.stringify(retval)).toBeTruthy();
  });

  it('#hasEmployerInput happy path', () => {
    const retval = component.hasEmployerInput();
    expect(retval).toBeTrue();
  });

  it('#getChildTransactionTitle happy path', () => {
    const retval = component.getChildTransactionTitle();
    expect(retval === 'Earmark memo').toBeTrue();
  });

  it('#test group methods to ensure they return the right values', () => {
    expect(component.childHasEmployerInput()).toBeTrue();
    expect(component.getParentTransactionTitle()).toBe('Receipt');
    expect(component.getParentFooter()).toBe('This type of receipt requires a memo transaction');
    expect(component.getGroupDescription()).toBe(
      'This type of receipt requires a memo transaction. Follow this two-step process to create both an earmark receipt and an earmark memo:'
    );
    expect(component.getParentAccordionTitle()).toBe('STEP ONE');
    expect(component.getParentAccordionSubTitle()).toBe('Add receipt and contributor information');
    expect(component.getChildAccordionSubTitle()).toBe(
      'Add earmarked memo and conduit information (REQUIRED FOR EARMARKED RECEIPTS)'
    );
    expect(component.getChildAccordionSubTitle()).toBe(
      'Add earmarked memo and conduit information (REQUIRED FOR EARMARKED RECEIPTS)'
    );
    expect(component.getPartTwoTitle()).toBe('STEP TWO');
    expect(component.getPartTwoSubTitle()).toBe(
      'Add earmarked memo and conduit information (REQUIRED FOR EARMARKED RECEIPTS)'
    );
    expect(component.getChildContactLabel()).toBe('Conduit');
    expect(component.getAutoGeneratedChildFields().length).toBe(0);
  });
});
