import { TestBed } from '@angular/core/testing';
import { LabelUtils } from 'app/shared/utils/label.utils';
import { testTemplateMap } from 'app/shared/utils/unit-test.utils';
import { ContactTypeLabels, ContactTypes } from '../contact.model';
import { TransactionGroupNM } from './transaction-group-nm.model';

describe('TransactionGroupNM', () => {
  let component: TransactionGroupNM;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [],
      providers: [TransactionGroupNM],
    });

    component = TestBed.inject(TransactionGroupNM);
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('#getFormProperties should include organization name', () => {
    const firstName = 'Joe';
    const lastName = 'Name';
    const testTemplateMapCopy = { ...testTemplateMap };
    testTemplateMapCopy.first_name = firstName;
    testTemplateMapCopy.last_name = lastName;
    const retval = component.getFormProperties(testTemplateMapCopy);
    expect(retval.includes(firstName)).toBeTruthy();
    expect(retval.includes(lastName)).toBeTruthy();
  });

  it('#getChildFormProperties should include organization name', () => {
    const testOrgName = 'org name';
    const testTemplateMapCopy = { ...testTemplateMap };
    testTemplateMapCopy.organization_name = testOrgName;
    const retval = component.getChildFormProperties(testTemplateMapCopy);
    expect(retval.includes(testOrgName)).toBeTruthy();
  });

  it('#getContactTypeOptions should return committee', () => {
    const expectedRetval = LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.INDIVIDUAL]);
    const retval = component.getContactTypeOptions();
    expect(JSON.stringify(expectedRetval) === JSON.stringify(retval)).toBeTruthy();
  });

  it('#getChildContactTypeOptions should return committee', () => {
    const expectedOptions = LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.COMMITTEE]);
    const options = component.getChildContactTypeOptions();
    expect(JSON.stringify(expectedOptions) === JSON.stringify(options)).toBeTruthy();
  });

  it('#hasEmployerInput should return false', () => {
    const retval = component.hasEmployerInput();
    expect(retval).toBeTrue();
  });

  it('#test group methods to ensure they return the right values', () => {
    expect(component.childHasEmployerInput()).toBeFalse();
    expect(component.getParentTransactionTitle()).toBe('Conduit Earmark Receipt');
    expect(component.getParentFooter()).toBe('This type of receipt requires a conduit earmark out.');
    expect(component.getGroupDescription()).toBe(
      'This receipt type requires an associated transaction. Follow this two-step process to create both a conduit earmark receipt and a conduit earmark out:'
    );
    expect(component.getParentAccordionTitle()).toBe('STEP ONE');
    expect(component.getParentAccordionSubTitle()).toBe('Add contact and receipt information');
    expect(component.getChildAccordionTitle()).toBe('STEP TWO');
    expect(component.getChildAccordionSubTitle()).toBe(
      'Add earmarked memo and conduit information (REQUIRED FOR CONDUIT EARMARKED RECEIPTS)'
    );
    expect(component.getChildContactLabel()).toBe('Contact');
    expect(component.getAutoGeneratedChildFields(testTemplateMap).length).toBe(1);
    expect(component.getChildTransactionSubTitle()).toBe(
      'To update any errors found, return to the previous step to update the in-kind receipt.'
    );
  });
});
