import { LabelUtils, PrimeOptions } from 'app/shared/utils/label.utils';
import { ContactTypeLabels, ContactTypes } from '../contact.model';
import { TransactionTemplateMapType } from '../transaction-type.model';
import { DoubleTransactionGroup } from './double-transaction-group.model';

export class TransactionGroupNM extends DoubleTransactionGroup {
  getFormProperties(templateMap: TransactionTemplateMapType): string[] {
    return [
      'entity_type',
      templateMap.last_name,
      templateMap.first_name,
      templateMap.middle_name,
      templateMap.prefix,
      templateMap.suffix,
      templateMap.street_1,
      templateMap.street_2,
      templateMap.city,
      templateMap.state,
      templateMap.zip,
      templateMap.date,
      templateMap.amount,
      templateMap.purpose_description,
      templateMap.employer,
      templateMap.occupation,
      templateMap.memo_code,
      templateMap.text4000,
    ].filter((field) => !!field);
  }

  getChildFormProperties(childTemplateMap: TransactionTemplateMapType): string[] {
    return [
      'entity_type',
      childTemplateMap.organization_name,
      childTemplateMap.committee_name,
      childTemplateMap.committee_fec_id,
      childTemplateMap.street_1,
      childTemplateMap.street_2,
      childTemplateMap.city,
      childTemplateMap.state,
      childTemplateMap.zip,
      childTemplateMap.date,
      childTemplateMap.amount,
      childTemplateMap.election_code,
      childTemplateMap.election_other_description,
      childTemplateMap.candidate_fec_id,
      childTemplateMap.candidate_last_name,
      childTemplateMap.candidate_first_name,
      childTemplateMap.candidate_middle_name,
      childTemplateMap.candidate_prefix,
      childTemplateMap.candidate_suffix,
      childTemplateMap.candidate_office,
      childTemplateMap.candidate_state,
      childTemplateMap.candidate_district,
      childTemplateMap.purpose_description,
      childTemplateMap.category_code,
      childTemplateMap.memo_code,
      childTemplateMap.text4000,
    ].filter((field) => !!field);
  }

  getContactTypeOptions(): PrimeOptions {
    return LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.INDIVIDUAL]);
  }

  getChildContactTypeOptions(): PrimeOptions {
    return LabelUtils.getPrimeOptions(ContactTypeLabels, [ContactTypes.COMMITTEE]);
  }

  hasEmployerInput(): boolean {
    return true;
  }

  override childHasEmployerInput(): boolean {
    return false;
  }

  getParentTransactionTitle(): string {
    return 'Conduit Earmark Receipt';
  }

  getParentFooter(): string {
    return 'This type of receipt requires a conduit earmark out.';
  }

  getChildTransactionSubTitle(): string {
    return 'To update any errors found, return to the previous step to update the in-kind receipt.';
  }

  getGroupDescription(): string {
    return 'This receipt type requires an associated transaction. Follow this two-step process to create both a conduit earmark receipt and a conduit earmark out:';
  }

  getParentAccordionTitle(): string {
    return 'STEP ONE';
  }

  getParentAccordionSubTitle(): string {
    return 'Add contact and receipt information';
  }

  getChildAccordionTitle(): string {
    return 'STEP TWO';
  }

  getChildAccordionSubTitle(): string {
    return 'Add earmarked memo and conduit information (REQUIRED FOR CONDUIT EARMARKED RECEIPTS)';
  }

  getChildContactLabel(): string {
    return 'Contact';
  }

  getAutoGeneratedChildFields(childTemplateMap: TransactionTemplateMapType): string[] {
    return [childTemplateMap.amount];
  }

  hasChildCandidateInformationInput(): boolean {
    return true;
  }

  hasChildElectionInformationInput(): boolean {
    return true;
  }

  hasParentCandidateInformationInput(): boolean {
    return false;
  }

  hasParentElectionInformationInput(): boolean {
    return false;
  }
}
